# Generated by Django 3.2 on 2022-01-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse', '0003_auto_20220107_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
    ]
