# Generated by Django 3.2 on 2022-01-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse', '0004_alter_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='business_license_register_id',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='corp_id',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='id',
        ),
        migrations.AlterField(
            model_name='measurements',
            name='size_in_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
